import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // ERP Design System Colors
        'surface-dim': '#d3daea',
        'surface-container-lowest': '#ffffff',
        'tertiary': '#825100',
        'secondary-fixed-dim': '#4edea3',
        'secondary-container': '#6cf8bb',
        'tertiary-fixed': '#ffddb8',
        'on-error-container': '#93000a',
        'on-secondary-container': '#00714d',
        'on-primary-fixed': '#001a42',
        'inverse-primary': '#adc6ff',
        'surface-container': '#e7eefe',
        'secondary-fixed': '#6ffbbe',
        'on-primary': '#ffffff',
        'tertiary-container': '#a36700',
        'secondary': '#006c49',
        'on-secondary-fixed': '#002113',
        'primary-fixed': '#d8e2ff',
        'on-background': '#151c27',
        'on-primary-fixed-variant': '#004395',
        'on-tertiary-fixed': '#2a1700',
        'primary-fixed-dim': '#adc6ff',
        'outline': '#727785',
        'surface-container-highest': '#dce2f3',
        'tertiary-fixed-dim': '#ffb95f',
        'error': '#ba1a1a',
        'on-surface-variant': '#424754',
        'inverse-surface': '#2a313d',
        'on-primary-container': '#fefcff',
        'inverse-on-surface': '#ebf1ff',
        'on-secondary-fixed-variant': '#005236',
        'primary': '#0058be',
        'primary-container': '#2170e4',
        'on-tertiary-container': '#fffbff',
        'surface': '#f9f9ff',
        'surface-bright': '#f9f9ff',
        'background': '#f9f9ff',
        'on-tertiary': '#ffffff',
        'on-secondary': '#ffffff',
        'outline-variant': '#c2c6d6',
        'surface-variant': '#dce2f3',
        'surface-tint': '#005ac2',
        'on-surface': '#151c27',
        'surface-container-high': '#e2e8f8',
        'on-error': '#ffffff',
        'surface-container-low': '#f0f3ff',
        'error-container': '#ffdad6',
        'on-tertiary-fixed-variant': '#653e00',
        'auth-blue': '#3B82F6',
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem',
      },
      spacing: {
        'md': '1rem',
        'lg': '1.5rem',
        'margin-desktop': '1.5rem',
        'max-width': '1600px',
        'sm': '0.75rem',
        'xs': '0.5rem',
        'gutter': '1rem',
        'xl': '2rem',
        'xxs': '0.25rem',
      },
      fontFamily: {
        'title-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'title-md': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'headline-sm': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'data-tabular': ['Inter', 'monospace'],
        'headline-lg': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'title-lg': ['18px', { lineHeight: '24px', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'title-md': ['16px', { lineHeight: '24px', fontWeight: '500' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'data-tabular': ['13px', { lineHeight: '16px', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};

export default config;
