import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      // Couleurs ERP fidèles au HTML original
      colors: {
        "surface-dim": "#d3daea",
        "surface-container-lowest": "#ffffff",
        "tertiary": "#825100",
        "secondary-fixed-dim": "#4edea3",
        "secondary-container": "#6cf8bb",
        "tertiary-fixed": "#ffddb8",
        "on-error-container": "#93000a",
        "on-secondary-container": "#00714d",
        "on-primary-fixed": "#001a42",
        "inverse-primary": "#adc6ff",
        "surface-container": "#e7eefe",
        "secondary-fixed": "#6ffbbe",
        "on-primary": "#ffffff",
        "tertiary-container": "#a36700",
        "secondary": "#006c49",
        "on-secondary-fixed": "#002113",
        "primary-fixed": "#d8e2ff",
        "on-background": "#151c27",
        "on-primary-fixed-variant": "#004395",
        "on-tertiary-fixed": "#2a1700",
        "primary-fixed-dim": "#adc6ff",
        "outline": "#727785",
        "surface-container-highest": "#dce2f3",
        "tertiary-fixed-dim": "#ffb95f",
        "error": "#ba1a1a",
        "on-surface-variant": "#424754",
        "inverse-surface": "#2a313d",
        "on-primary-container": "#fefcff",
        "inverse-on-surface": "#ebf1ff",
        "on-secondary-fixed-variant": "#005236",
        "primary": "#0058be",
        "primary-container": "#2170e4",
        "on-tertiary-container": "#fffbff",
        "surface": "#f9f9ff",
        "surface-bright": "#f9f9ff",
        "background": "#f9f9ff",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "outline-variant": "#c2c6d6",
        "surface-variant": "#dce2f3",
        "surface-tint": "#005ac2",
        "on-surface": "#151c27",
        "surface-container-high": "#e2e8f8",
        "on-error": "#ffffff",
        "surface-container-low": "#f0f3ff",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#653e00",
        "auth-blue": "#3B82F6",

        // Couleurs Kamlog métier
        kamlog: {
          primary: {
            DEFAULT: "#0058be",
            hover: "#004395",
          },
          secondary: "#006c49",
          accent: "#825100",
          danger: "#ba1a1a",
          success: "#006c49",
          warning: "#825100",
          info: "#0058be",
        },
        statut: {
          planifie: "#006c49",
          "en-chargement": "#825100",
          "en-route": "#0058be",
          "en-livraison": "#3B82F6",
          livre: "#006c49",
          cloture: "#727785",
        },
        yard: {
          libre: "#006c49",
          occupe: "#ba1a1a",
          reserve: "#825100",
          blocked: "#727785",
        },
      },
      // BorderRadius ERP
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem", 
        xl: "0.5rem",
        full: "0.75rem",
      },
      // Spacing ERP fidèle au HTML
      spacing: {
        md: "1rem",
        lg: "1.5rem",
        "margin-desktop": "1.5rem",
        "max-width": "1600px",
        sm: "0.75rem",
        xs: "0.5rem",
        gutter: "1rem",
        xl: "2rem",
        xxs: "0.25rem",
      },
      // Fonts ERP
      fontFamily: {
        "title-lg": ["Inter"],
        "headline-md": ["Inter"],
        "body-sm": ["Inter"],
        "body-md": ["Inter"],
        "title-md": ["Inter"],
        "label-md": ["Inter"],
        "headline-sm": ["Inter"],
        "body-lg": ["Inter"],
        "label-sm": ["Inter"],
        "data-tabular": ["Inter"],
        "headline-lg": ["Inter"],
        sans: ["Inter", "system-ui", "sans-serif"],
      },
    },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/forms")],
};
export default config;