// src/app/(app)/auth/mfa-verification/page.tsx - MFA Verification - Fidèle 100% au HTML original
'use client'

import { useState, useEffect, useRef } from 'react'

export default function MFAVerification() {
  const [view, setView] = useState<'totp' | 'setup'>('totp')
  const [code, setCode] = useState(['', '', '', '', '', ''])
  const inputRefs = useRef<(HTMLInputElement | null)[]>([])

  useEffect(() => {
    if (inputRefs.current[0]) {
      inputRefs.current[0].focus()
    }
  }, [])

  const handleInputChange = (index: number, value: string) => {
    if (!/^\d*$/.test(value)) return
    
    const newCode = [...code]
    newCode[index] = value
    setCode(newCode)
    
    if (value.length === 1 && index < 5 && inputRefs.current[index + 1]) {
      inputRefs.current[index + 1]?.focus()
    }
  }

  const handleKeyDown = (index: number, e: React.KeyboardEvent) => {
    if (e.key === 'Backspace' && !code[index] && index > 0 && inputRefs.current[index - 1]) {
      inputRefs.current[index - 1]?.focus()
    }
  }

  const toggleView = (viewId: 'totp' | 'setup') => {
    setView(viewId)
    if (viewId === 'totp' && inputRefs.current[0]) {
      setTimeout(() => inputRefs.current[0]?.focus(), 100)
    }
  }

  return (
    <>
      <style jsx global>{`
        .material-symbols-outlined {
          font-variation-settings: 'FILL 0, wght 400, GRAD 0, opsz 24';
        }
        .icon-fill {
          font-variation-settings: 'FILL 1';
        }
        .mfa-input:focus {
          outline: none;
          border-color: #0058be;
          box-shadow: 0 0 0 2px rgba(0, 88, 190, 0.1);
        }
        .shimmer-effect {
          background: linear-gradient(90deg, rgba(255,255,255,0) 0%, rgba(255,255,255,0.4) 50%, rgba(255,255,255,0) 100%);
          background-size: 200% 100%;
          animation: shimmer 3s infinite linear;
        }
        @keyframes shimmer {
          0% { background-position: -200% 0; }
          100% { background-position: 200% 0; }
        }
      `}</style>
      <div className="bg-surface-container-low text-on-surface font-body-md min-h-screen flex flex-col">
        {/* TopNavBar */}
        <header className="fixed top-0 left-0 w-full z-50 flex justify-between items-center px-lg h-16 bg-surface-container-low border-b border-outline-variant">
          <div className="flex items-center gap-xs">
            <span className="text-primary font-bold text-title-lg tracking-tight">KAMLOG EM-ERP</span>
          </div>
          <div className="flex items-center gap-md">
            <div className="flex flex-col items-end hidden md:flex">
              <span className="text-label-md font-label-md text-primary uppercase tracking-widest">Secure Gateway</span>
              <span className="text-label-sm font-label-sm text-on-surface-variant">Session: Pending MFA</span>
            </div>
            <span className="material-symbols-outlined text-outline">security</span>
          </div>
        </header>
        <main className="flex-grow flex items-center justify-center pt-16 px-md relative overflow-hidden">
          {/* Background Atmospheric Element */}
          <div className="absolute inset-0 z-0 opacity-40"></div>
          <div className="relative z-10 w-full max-w-[480px] bg-white border border-outline-variant rounded-xl shadow-sm overflow-hidden flex flex-col">
            {/* Header Section */}
            <div className="p-lg bg-surface-container-high/50 border-b border-outline-variant flex items-center gap-md">
              <div className="w-12 h-12 rounded-lg bg-primary-container flex items-center justify-center text-on-primary-container">
                <span className="material-symbols-outlined text-[28px] icon-fill">lock_person</span>
              </div>
              <div>
                <h1 className="text-headline-sm font-headline-sm text-on-surface">MFA Verification</h1>
                <p className="text-body-sm text-on-surface-variant">Two-step authentication required</p>
              </div>
            </div>
            <div className="p-lg space-y-xl">
              {/* TOTP Verification Form */}
              <div className={`space-y-lg ${view === 'totp' ? '' : 'hidden'}`} id="totp-view">
                <div className="space-y-xs">
                  <p className="text-body-md text-on-surface font-medium">Enter 6-digit code</p>
                  <p className="text-body-sm text-on-surface-variant leading-relaxed">Enter the dynamic verification code generated by your mobile authenticator app to proceed.</p>
                </div>
                <div className="flex justify-between gap-xxs" id="mfa-inputs">
                  <input 
                    ref={el => { inputRefs.current[0] = el }}
                    className="mfa-input w-12 h-14 text-center text-headline-sm font-bold border border-outline-variant rounded bg-surface-container-lowest focus:border-primary transition-all" 
                    inputMode="numeric" 
                    maxLength={1} 
                    pattern="\d*" 
                    type="text"
                    value={code[0]}
                    onChange={(e) => handleInputChange(0, e.target.value)}
                    onKeyDown={(e) => handleKeyDown(0, e)}
                  />
                  <input 
                    ref={el => { inputRefs.current[1] = el }}
                    className="mfa-input w-12 h-14 text-center text-headline-sm font-bold border border-outline-variant rounded bg-surface-container-lowest focus:border-primary transition-all" 
                    inputMode="numeric" 
                    maxLength={1} 
                    pattern="\d*" 
                    type="text"
                    value={code[1]}
                    onChange={(e) => handleInputChange(1, e.target.value)}
                    onKeyDown={(e) => handleKeyDown(1, e)}
                  />
                  <input 
                    ref={el => { inputRefs.current[2] = el }}
                    className="mfa-input w-12 h-14 text-center text-headline-sm font-bold border border-outline-variant rounded bg-surface-container-lowest focus:border-primary transition-all" 
                    inputMode="numeric" 
                    maxLength={1} 
                    pattern="\d*" 
                    type="text"
                    value={code[2]}
                    onChange={(e) => handleInputChange(2, e.target.value)}
                    onKeyDown={(e) => handleKeyDown(2, e)}
                  />
                  <div className="flex items-center text-outline-variant">
                    <span className="w-3 h-[2px] bg-current"></span>
                  </div>
                  <input 
                    ref={el => { inputRefs.current[3] = el }}
                    className="mfa-input w-12 h-14 text-center text-headline-sm font-bold border border-outline-variant rounded bg-surface-container-lowest focus:border-primary transition-all" 
                    inputMode="numeric" 
                    maxLength={1} 
                    pattern="\d*" 
                    type="text"
                    value={code[3]}
                    onChange={(e) => handleInputChange(3, e.target.value)}
                    onKeyDown={(e) => handleKeyDown(3, e)}
                  />
                  <input 
                    ref={el => { inputRefs.current[4] = el }}
                    className="mfa-input w-12 h-14 text-center text-headline-sm font-bold border border-outline-variant rounded bg-surface-container-lowest focus:border-primary transition-all" 
                    inputMode="numeric" 
                    maxLength={1} 
                    pattern="\d*" 
                    type="text"
                    value={code[4]}
                    onChange={(e) => handleInputChange(4, e.target.value)}
                    onKeyDown={(e) => handleKeyDown(4, e)}
                  />
                  <input 
                    ref={el => { inputRefs.current[5] = el }}
                    className="mfa-input w-12 h-14 text-center text-headline-sm font-bold border border-outline-variant rounded bg-surface-container-lowest focus:border-primary transition-all" 
                    inputMode="numeric" 
                    maxLength={1} 
                    pattern="\d*" 
                    type="text"
                    value={code[5]}
                    onChange={(e) => handleInputChange(5, e.target.value)}
                    onKeyDown={(e) => handleKeyDown(5, e)}
                  />
                </div>
                <button className="w-full h-12 bg-primary text-on-primary font-bold rounded flex items-center justify-center gap-xs hover:bg-primary-container transition-all active:scale-[0.98]">
                  <span>Verify & Login</span>
                  <span className="material-symbols-outlined text-[20px]">arrow_forward</span>
                </button>
                <div className="pt-sm border-t border-outline-variant flex flex-col gap-sm text-center">
                  <a className="text-body-sm text-primary font-medium hover:underline flex items-center justify-center gap-xxs" href="#">
                    <span className="material-symbols-outlined text-[16px]">key</span>
                    Enter backup code
                  </a>
                  <button 
                    className="text-body-sm text-on-surface-variant hover:text-on-surface transition-colors flex items-center justify-center gap-xxs"
                    onClick={() => toggleView('setup')}
                  >
                    <span className="material-symbols-outlined text-[16px]">qr_code_2</span>
                    First time? Set up QR code
                  </button>
                </div>
              </div>
              {/* QR Setup View */}
              <div className={`hidden space-y-lg ${view === 'setup' ? '' : 'hidden'}`} id="setup-view">
                <div className="space-y-xs">
                  <p className="text-body-md text-on-surface font-medium">Authenticator Setup</p>
                  <p className="text-body-sm text-on-surface-variant leading-relaxed">Scan this QR code with Google Authenticator or Microsoft Authenticator to link your account.</p>
                </div>
                <div className="flex justify-center p-md bg-white border-2 border-dashed border-outline-variant rounded-lg">
                  <div className="relative w-48 h-48">
                    <img alt="MFA QR Code" className="w-full h-full" src="https://lh3.googleusercontent.com/aida-public/AB6AXuDIS9VvST_w4csvB_WyzL51UgVvEtNrTwb7Gz7EDGHw3EsJ_SQF3FAYEjPYHkPkL6v29rKilEMHViorLbF7h0wEzU7ISIPvtXVCNh-YjDPM3vULBB4332dbeD8iSkPKuJYYUoGk1KGa65TgLX66YoM80OP4OLWkmD4ItAywKijz7-CNVmXYh07_wz9niZH5-ebfMuoR1FaVC7OY4kPIgCGLSfnxCICCd5rQUcy0niATowDASgtqeJ0MszVaeR3hdrUFLOwHsGu_U34"/>
                    {/* Scanning Shimmer */}
                    <div className="absolute inset-0 shimmer-effect opacity-30 pointer-events-none"></div>
                  </div>
                </div>
                <div className="bg-surface-container p-sm rounded border border-outline-variant/30">
                  <p className="text-label-sm font-label-sm text-on-surface-variant uppercase tracking-wider mb-xxs">Manual Secret Key</p>
                  <p className="text-data-tabular font-mono text-on-surface break-all bg-surface-container-lowest p-xs border border-outline-variant rounded select-all">JBSW Y3DP EBLW 64TJ M5SS K7TG</p>
                </div>
                <div className="flex gap-sm">
                  <button 
                    className="flex-1 h-11 border border-outline text-on-surface font-medium rounded hover:bg-surface-container-high transition-all"
                    onClick={() => toggleView('totp')}
                  >
                    Back to Verify
                  </button>
                  <button className="flex-1 h-11 bg-primary text-on-primary font-bold rounded hover:bg-primary-container transition-all">
                    Complete Setup
                  </button>
                </div>
              </div>
            </div>
            {/* Footer Compliance */}
            <div className="px-lg py-md bg-surface-container-lowest text-center">
              <p className="text-label-sm font-label-sm text-on-surface-variant">KAMLOG Secure Access Control © 2026</p>
              <div className="flex justify-center gap-md mt-xxs">
                <span className="text-label-sm text-outline flex items-center gap-xxs">
                  <span className="material-symbols-outlined text-[14px] icon-fill">verified_user</span> 
                  ISO 27001 Compliant
                </span>
              </div>
            </div>
          </div>
        </main>
        {/* Visual Identity Strip */}
        <div className="fixed bottom-0 left-0 w-full h-1 bg-primary flex">
          <div className="h-full bg-secondary w-1/4"></div>
          <div className="h-full bg-tertiary-container w-1/4"></div>
          <div className="h-full bg-primary w-2/4"></div>
        </div>
      </div>
    </>
  )
}
