"""Add fuel and workshop models

Revision ID: 3a9461e2fd78
Revises: 5f1f9590b2f3
Create Date: 2026-07-02 08:36:55.287413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a9461e2fd78'
down_revision = '5f1f9590b2f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reparations_atelier',
    sa.Column('reference', sa.String(length=30), nullable=False),
    sa.Column('camion_id', sa.Integer(), nullable=False),
    sa.Column('type_intervention', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('statut', sa.String(length=30), nullable=False),
    sa.Column('cout_estime', sa.Integer(), nullable=True),
    sa.Column('date_entree', sa.String(length=50), nullable=False),
    sa.Column('date_sortie_prevue', sa.String(length=50), nullable=True),
    sa.Column('mecanicien_en_charge', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reparations_atelier')),
    sa.UniqueConstraint('reference', name=op.f('uq_reparations_atelier_reference'))
    )
    op.create_table('tickets_carburant',
    sa.Column('camion_id', sa.Integer(), nullable=False),
    sa.Column('chauffeur_id', sa.Integer(), nullable=False),
    sa.Column('quantite_litres', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('prix_unitaire', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('montant_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('date_plein', sa.String(length=50), nullable=False),
    sa.Column('kilometrage', sa.Integer(), nullable=False),
    sa.Column('station_service', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['camion_id'], ['camions_flotte.id'], name=op.f('fk_tickets_carburant_camion_id_camions_flotte')),
    sa.ForeignKeyConstraint(['chauffeur_id'], ['chauffeurs.id'], name=op.f('fk_tickets_carburant_chauffeur_id_chauffeurs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tickets_carburant'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets_carburant')
    op.drop_table('reparations_atelier')
    # ### end Alembic commands ###
