"""Add soft delete is_deleted to BaseModel

Revision ID: 70ce49c04485
Revises: 4e60fe009c10
Create Date: 2026-07-02 02:25:20.416385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70ce49c04485'
down_revision = '4e60fe009c10'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agencies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False))

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False))

    with op.batch_alter_table('avoirs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False))

    with op.batch_alter_table('camions_flotte', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False))

    with op.batch_alter_table('chauffeurs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False))

    with op.batch_alter_table('commande_factures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False))

    with op.batch_alter_table('commande_livraisons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False))

    with op.batch_alter_table('dossiers_operationnels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False))

    with op.batch_alter_table('emplacements_parc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False))

    with op.batch_alter_table('encaissements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False))

    with op.batch_alter_table('facture_paiements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False))

    with op.batch_alter_table('factures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False))

    with op.batch_alter_table('grilles_tarifaires', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False))

    with op.batch_alter_table('idempotency_keys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False))

    with op.batch_alter_table('mission_factures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False))

    with op.batch_alter_table('missions_transport', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False))

    with op.batch_alter_table('mouvements_parc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False))

    with op.batch_alter_table('notifications_destinations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False))

    with op.batch_alter_table('passerelles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False))

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False))

    with op.batch_alter_table('reception_stocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False))

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False))

    with op.batch_alter_table('stock_physique_parc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False))

    with op.batch_alter_table('tiers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False))

    with op.batch_alter_table('zones_parc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zones_parc', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('tiers', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('stock_physique_parc', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('reception_stocks', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('passerelles', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('notifications_destinations', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('mouvements_parc', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('missions_transport', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('mission_factures', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('idempotency_keys', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('grilles_tarifaires', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('factures', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('facture_paiements', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('encaissements', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('emplacements_parc', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('dossiers_operationnels', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('commande_livraisons', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('commande_factures', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('chauffeurs', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('camions_flotte', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('avoirs', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('agencies', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
