"""add_plan_field_to_agency

Revision ID: add_plan_field_to_agency
Revises: b938459a1234
Create Date: 2026-07-18 02:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_plan_field_to_agency'
down_revision = 'b938459a1234'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the ENUM type first
    plan_enum = postgresql.ENUM('BASIC', 'PROFESSIONAL', 'ENTERPRISE', name='plantype')
    plan_enum.create(op.get_bind())

    # Add the plan column to agencies table
    op.add_column('agencies', sa.Column('plan', plan_enum, nullable=False, server_default='BASIC'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the plan column
    op.drop_column('agencies', 'plan')
    # Drop the ENUM type
    plan_enum = postgresql.ENUM('BASIC', 'PROFESSIONAL', 'ENTERPRISE', name='plantype')
    plan_enum.drop(op.get_bind())
    # ### end Alembic commands ###