"""add_plan_permissions

Revision ID: add_plan_permissions
Revises: add_plan_field_to_agency
Create Date: 2026-07-18 02:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_plan_permissions'
down_revision = 'add_plan_field_to_agency'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Insert plan-based permissions
    permissions = [
        # BASIC features (available to all plans, but explicit for clarity)
        ('feature:basic_article_management', 'Basic Article Management', 'features'),
        ('feature:basic_client_management', 'Basic Client Management', 'features'),
        ('feature:basic_supplier_management', 'Basic Supplier Management', 'features'),
        ('feature:basic_invoicing', 'Basic Invoicing', 'features'),
        ('feature:basic_payments', 'Basic Payments', 'features'),
        ('feature:basic_reporting', 'Basic Reporting', 'features'),

        # PROFESSIONAL features
        ('feature:advanced_analytics', 'Advanced Analytics', 'features'),
        ('feature:multi_warehouse', 'Multi-Warehouse Management', 'features'),
        ('feature:advanced_procurement', 'Advanced Procurement', 'features'),
        ('feature:api_access', 'API Access', 'features'),
        ('feature:basic_ai', 'Basic AI Features', 'features'),
        ('feature:priority_support', 'Priority Support', 'features'),

        # ENTERPRISE features
        ('feature:full_ai_suite', 'Full AI Suite', 'features'),
        ('feature:unlimited_resources', 'Unlimited Resources', 'features'),
        ('feature:custom_integrations', 'Custom Integrations', 'features'),
        ('feature:dedicated_support', 'Dedicated Support', 'features'),
        ('feature:sla_guarantee', 'SLA Guarantee', 'features'),
        ('feature:on_premise_option', 'On-Premise Option', 'features'),
        ('feature:advanced_customization', 'Advanced Customization', 'features'),
        ('feature:white_labeling', 'White Labeling', 'features'),
    ]

    # Insert permissions using raw SQL for simplicity
    for code, name, module in permissions:
        op.execute(
            f"INSERT INTO permissions (code, name, module) VALUES ('{code}', '{name}', '{module}') "
            f"ON CONFLICT (code) DO NOTHING"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove plan-based permissions
    permission_codes = [
        'feature:basic_article_management',
        'feature:basic_client_management',
        'feature:basic_supplier_management',
        'feature:basic_invoicing',
        'feature:basic_payments',
        'feature:basic_reporting',
        'feature:advanced_analytics',
        'feature:multi_warehouse',
        'feature:advanced_procurement',
        'feature:api_access',
        'feature:basic_ai',
        'feature:priority_support',
        'feature:full_ai_suite',
        'feature:unlimited_resources',
        'feature:custom_integrations',
        'feature:dedicated_support',
        'feature:sla_guarantee',
        'feature:on_premise_option',
        'feature:advanced_customization',
        'feature:white_labeling',
    ]

    for code in permission_codes:
        op.execute(f"DELETE FROM permissions WHERE code = '{code}'")
    # ### end Alembic commands ###