"""add_module_based_permissions

Revision ID: add_module_based_permissions
Revises: add_plan_roles
Create Date: 2026-07-18 03:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_module_based_permissions'
down_revision = 'add_plan_roles'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Insert module-based permissions for router compatibility
    permissions = [
        # Transport permissions
        ('transport:read', 'Transport Read Access', 'transport'),
        ('transport:write', 'Transport Write Access', 'transport'),
        ('transport:delete', 'Transport Delete Access', 'transport'),

        # Finance permissions
        ('finance:read', 'Finance Read Access', 'finance'),
        ('finance:write', 'Finance Write Access', 'finance'),
        ('finance:delete', 'Finance Delete Access', 'finance'),
        ('finance:validate', 'Finance Validate Access', 'finance'),

        # Parc permissions
        ('parc:read', 'Parc Read Access', 'parc'),
        ('parc:write', 'Parc Write Access', 'parc'),
        ('parc:delete', 'Parc Delete Access', 'parc'),
        ('parc:gate', 'Parc Gate Access', 'parc'),

        # Purchase permissions
        ('purchase:read', 'Purchase Read Access', 'purchase'),
        ('purchase:write', 'Purchase Write Access', 'purchase'),
        ('purchase:create', 'Purchase Create Access', 'purchase'),
        ('purchase:update', 'Purchase Update Access', 'purchase'),
        ('purchase:delete', 'Purchase Delete Access', 'purchase'),
        ('purchase:submit', 'Purchase Submit Access', 'purchase'),
        ('purchase:approve', 'Purchase Approve Access', 'purchase'),

        # Notifications permissions
        ('notifications:read_all', 'Notifications Read All Access', 'notifications'),
        ('notifications:create', 'Notifications Create Access', 'notifications'),

        # RH permissions
        ('rh:read', 'RH Read Access', 'rh'),
        ('rh:write', 'RH Write Access', 'rh'),

        # Tiers permissions
        ('tiers:read', 'Tiers Read Access', 'tiers'),
        ('tiers:write', 'Tiers Write Access', 'tiers'),
        ('tiers:delete', 'Tiers Delete Access', 'tiers'),
    ]

    # Insert permissions using raw SQL for simplicity
    for code, name, module in permissions:
        op.execute(
            f"INSERT INTO permissions (code, name, module) VALUES ('{code}', '{name}', '{module}') "
            f"ON CONFLICT (code) DO NOTHING"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove module-based permissions
    permission_codes = [
        # Transport permissions
        'transport:read',
        'transport:write',
        'transport:delete',

        # Finance permissions
        'finance:read',
        'finance:write',
        'finance:delete',
        'finance:validate',

        # Parc permissions
        'parc:read',
        'parc:write',
        'parc:delete',
        'parc:gate',

        # Purchase permissions
        'purchase:read',
        'purchase:write',
        'purchase:create',
        'purchase:update',
        'purchase:delete',
        'purchase:submit',
        'purchase:approve',

        # Notifications permissions
        'notifications:read_all',
        'notifications:create',

        # RH permissions
        'rh:read',
        'rh:write',

        # Tiers permissions
        'tiers:read',
        'tiers:write',
        'tiers:delete',
    ]

    for code in permission_codes:
        op.execute(f"DELETE FROM permissions WHERE code = '{code}'")
    # ### end Alembic commands ###