"""rbac_multi_roles

Revision ID: 4e60fe009c10
Revises: bef112189395
Create Date: 2026-07-01 22:33:16.348299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e60fe009c10'
down_revision = 'bef112189395'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("""
        CREATE TABLE IF NOT EXISTS user_roles (
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            role_id INTEGER NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
            PRIMARY KEY (user_id, role_id)
        );
    """)

    op.execute("""
        DO $$ BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name='users' AND column_name='role'
            ) THEN
                ALTER TABLE users DROP COLUMN role;
            END IF;
        END $$;
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=50), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_users_role_roles'), 'roles', ['role'], ['code'])

    op.drop_table('user_roles')
    # ### end Alembic commands ###
