"""Add K-TRANSPORT extended schemas

Revision ID: 28ed111f3db5
Revises: 3a9461e2fd78
Create Date: 2026-07-02 21:07:40.445149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28ed111f3db5'
down_revision = '3a9461e2fd78'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('controles_hse',
    # sa.Column('vehicule_id', sa.Integer(), nullable=False),
    # sa.Column('controleur', sa.String(length=100), nullable=False),
    # sa.Column('date_controle', sa.DateTime(), nullable=False),
    # sa.Column('vehicule_bloque', sa.Boolean(), nullable=False),
    # sa.Column('motif_blocage', sa.Text(), nullable=True),
    # sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    # sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    # sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    # sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    # sa.ForeignKeyConstraint(['vehicule_id'], ['camions_flotte.id'], name=op.f('fk_controles_hse_vehicule_id_camions_flotte')),
    # sa.PrimaryKeyConstraint('id', name=op.f('pk_controles_hse'))
    # )
    # op.create_table('pannes_vehicule',
    # sa.Column('vehicule_id', sa.Integer(), nullable=False),
    # sa.Column('description', sa.Text(), nullable=False),
    # sa.Column('date_declaration', sa.DateTime(), nullable=False),
    # sa.Column('date_reparation_prevue', sa.Date(), nullable=True),
    # sa.Column('statut', sa.Enum('A_REPARER', 'EN_COURS', 'RESOLU', name='statutpanne'), nullable=False),
    # sa.Column('declare_par', sa.String(length=100), nullable=True),
    # sa.Column('notes_resolution', sa.Text(), nullable=True),
    # sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    # sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    # sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    # sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    # sa.ForeignKeyConstraint(['vehicule_id'], ['camions_flotte.id'], name=op.f('fk_pannes_vehicule_vehicule_id_camions_flotte')),
    # sa.PrimaryKeyConstraint('id', name=op.f('pk_pannes_vehicule'))
    # )
    # op.create_table('vehicule_documents',
    # sa.Column('vehicule_id', sa.Integer(), nullable=False),
    # sa.Column('type_document', sa.String(length=50), nullable=False),
    # sa.Column('numero', sa.String(length=100), nullable=False),
    # sa.Column('date_emission', sa.Date(), nullable=False),
    # sa.Column('date_expiration', sa.Date(), nullable=False),
    # sa.Column('fichier_url', sa.String(length=255), nullable=True),
    # sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    # sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    # sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    # sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    # sa.ForeignKeyConstraint(['vehicule_id'], ['camions_flotte.id'], name=op.f('fk_vehicule_documents_vehicule_id_camions_flotte')),
    # sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicule_documents'))
    # )
    # op.create_table('chauffeur_documents',
    # sa.Column('chauffeur_id', sa.Integer(), nullable=False),
    # sa.Column('type_document', sa.String(length=50), nullable=False),
    # sa.Column('numero', sa.String(length=100), nullable=False),
    # sa.Column('date_emission', sa.Date(), nullable=False),
    # sa.Column('date_expiration', sa.Date(), nullable=False),
    # sa.Column('fichier_url', sa.String(length=255), nullable=True),
    # sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    # sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    # sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    # sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    # sa.ForeignKeyConstraint(['chauffeur_id'], ['chauffeurs.id'], name=op.f('fk_chauffeur_documents_chauffeur_id_chauffeurs')),
    # sa.PrimaryKeyConstraint('id', name=op.f('pk_chauffeur_documents'))
    # )
    with op.batch_alter_table('camions_flotte', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_materiel', sa.Enum('TRACTEUR', 'REMORQUE', 'SEMI_REMORQUE', name='typemateriel'), server_default='TRACTEUR', nullable=False))
        batch_op.add_column(sa.Column('gps_tracker_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('remorque_id', sa.Integer(), nullable=True))
        batch_op.alter_column('volume_reservoir_litres',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               nullable=True)
        batch_op.alter_column('conso_theorique_l_100',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               nullable=True)
        batch_op.alter_column('statut',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('DISPONIBLE', 'EN_MAINTENANCE', 'EN_ROUTE', 'EN_CHARGEMENT', 'BLOQUE_HSE', name='statutcamion'),
               existing_nullable=False)
        batch_op.create_unique_constraint(batch_op.f('uq_camions_flotte_gps_tracker_id'), ['gps_tracker_id'])
        batch_op.create_foreign_key(batch_op.f('fk_camions_flotte_remorque_id_camions_flotte'), 'camions_flotte', ['remorque_id'], ['id'])

    with op.batch_alter_table('chauffeurs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adresse', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('contact_urgence_nom', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('contact_urgence_telephone', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('statut', sa.Enum('EN_SERVICE', 'EN_REPOS', 'EN_MISSION', 'EN_FORMATION', name='statutchauffeur'), server_default='EN_SERVICE', nullable=False))
        batch_op.add_column(sa.Column('affectation_vehicule_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('specialisation', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('date_entree', sa.Date(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_chauffeurs_affectation_vehicule_id_camions_flotte'), 'camions_flotte', ['affectation_vehicule_id'], ['id'])

    with op.batch_alter_table('missions_transport', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expediteur_adresse', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('destinataire_adresse', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('contact_site', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('remorque_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('nature_fret', sa.String(length=50), server_default='INCONNU', nullable=False))
        batch_op.add_column(sa.Column('volume_m3', sa.Numeric(precision=10, scale=3), nullable=True))
        batch_op.add_column(sa.Column('date_chargement_prevue', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('date_livraison_souhaitee', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('montant_fret', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('frais_peage', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('frais_annexes', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_missions_transport_remorque_id_camions_flotte'), 'camions_flotte', ['remorque_id'], ['id'])
        batch_op.drop_column('type_marchandise')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('missions_transport', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_marchandise', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_missions_transport_remorque_id_camions_flotte'), type_='foreignkey')
        batch_op.drop_column('frais_annexes')
        batch_op.drop_column('frais_peage')
        batch_op.drop_column('montant_fret')
        batch_op.drop_column('date_livraison_souhaitee')
        batch_op.drop_column('date_chargement_prevue')
        batch_op.drop_column('volume_m3')
        batch_op.drop_column('nature_fret')
        batch_op.drop_column('remorque_id')
        batch_op.drop_column('contact_site')
        batch_op.drop_column('destinataire_adresse')
        batch_op.drop_column('expediteur_adresse')

    with op.batch_alter_table('chauffeurs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_chauffeurs_affectation_vehicule_id_camions_flotte'), type_='foreignkey')
        batch_op.drop_column('date_entree')
        batch_op.drop_column('specialisation')
        batch_op.drop_column('affectation_vehicule_id')
        batch_op.drop_column('statut')
        batch_op.drop_column('contact_urgence_telephone')
        batch_op.drop_column('contact_urgence_nom')
        batch_op.drop_column('adresse')

    with op.batch_alter_table('camions_flotte', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_camions_flotte_remorque_id_camions_flotte'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_camions_flotte_gps_tracker_id'), type_='unique')
        batch_op.alter_column('statut',
               existing_type=sa.Enum('DISPONIBLE', 'EN_MAINTENANCE', 'EN_ROUTE', 'EN_CHARGEMENT', 'BLOQUE_HSE', name='statutcamion'),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
        batch_op.alter_column('conso_theorique_l_100',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               nullable=False)
        batch_op.alter_column('volume_reservoir_litres',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               nullable=False)
        batch_op.drop_column('remorque_id')
        batch_op.drop_column('gps_tracker_id')
        batch_op.drop_column('type_materiel')

    op.drop_table('chauffeur_documents')
    op.drop_table('vehicule_documents')
    op.drop_table('pannes_vehicule')
    op.drop_table('controles_hse')
    # ### end Alembic commands ###
