"""add_module_based_permissions_to_roles

Revision ID: add_module_based_permissions_to_roles
Revises: add_module_based_permissions
Create Date: 2026-07-18 03:45:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_module_based_permissions_to_roles'
down_revision = 'add_module_based_permissions'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Assign module-based permissions to plan-based roles

    # BASIC_USER permissions - basic read access
    basic_user_permissions = [
        # Transport
        'transport:read',
        # Finance
        'finance:read',
        # Parc
        'parc:read',
        # Purchase
        'purchase:read',
        # Notifications
        'notifications:read_all',
        # RH
        'rh:read',
        # Tiers
        'tiers:read',
    ]

    for permission_code in basic_user_permissions:
        op.execute(
            f"INSERT INTO role_permissions (role_id, permission_id) "
            f"SELECT r.id, p.id FROM roles r, permissions p "
            f"WHERE r.code = 'BASIC_USER' AND p.code = '{permission_code}' "
            f"ON CONFLICT DO NOTHING"
        )

    # PROFESSIONAL_USER permissions - includes BASIC + write access
    professional_user_permissions = [
        # Transport
        'transport:read', 'transport:write',
        # Finance
        'finance:read', 'finance:write', 'finance:validate',
        # Parc
        'parc:read', 'parc:write', 'parc:gate',
        # Purchase
        'purchase:read', 'purchase:write', 'purchase:create', 'purchase:update',
        # Notifications
        'notifications:read_all', 'notifications:create',
        # RH
        'rh:read', 'rh:write',
        # Tiers
        'tiers:read', 'tiers:write',
    ]

    for permission_code in professional_user_permissions:
        op.execute(
            f"INSERT INTO role_permissions (role_id, permission_id) "
            f"SELECT r.id, p.id FROM roles r, permissions p "
            f"WHERE r.code = 'PROFESSIONAL_USER' AND p.code = '{permission_code}' "
            f"ON CONFLICT DO NOTHING"
        )

    # ENTERPRISE_USER permissions - includes PROFESSIONAL + full access
    enterprise_user_permissions = [
        # Transport
        'transport:read', 'transport:write', 'transport:delete',
        # Finance
        'finance:read', 'finance:write', 'finance:delete', 'finance:validate',
        # Parc
        'parc:read', 'parc:write', 'parc:delete', 'parc:gate',
        # Purchase
        'purchase:read', 'purchase:write', 'purchase:create', 'purchase:update', 'purchase:delete', 'purchase:submit', 'purchase:approve',
        # Notifications
        'notifications:read_all', 'notifications:create',
        # RH
        'rh:read', 'rh:write',
        # Tiers
        'tiers:read', 'tiers:write', 'tiers:delete',
    ]

    for permission_code in enterprise_user_permissions:
        op.execute(
            f"INSERT INTO role_permissions (role_id, permission_id) "
            f"SELECT r.id, p.id FROM roles r, permissions p "
            f"WHERE r.code = 'ENTERPRISE_USER' AND p.code = '{permission_code}' "
            f"ON CONFLICT DO NOTHING"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove module-based permission assignments from plan-based roles

    # Remove BASIC_USER module-based permissions
    basic_user_permissions = [
        'transport:read', 'finance:read', 'parc:read', 'purchase:read',
        'notifications:read_all', 'rh:read', 'tiers:read'
    ]

    for permission_code in basic_user_permissions:
        op.execute(
            f"DELETE FROM role_permissions "
            f"WHERE role_id IN (SELECT id FROM roles WHERE code = 'BASIC_USER') "
            f"AND permission_id IN (SELECT id FROM permissions WHERE code = '{permission_code}')"
        )

    # Remove PROFESSIONAL_USER module-based permissions
    professional_user_permissions = [
        'transport:read', 'transport:write',
        'finance:read', 'finance:write', 'finance:validate',
        'parc:read', 'parc:write', 'parc:gate',
        'purchase:read', 'purchase:write', 'purchase:create', 'purchase:update',
        'notifications:read_all', 'notifications:create',
        'rh:read', 'rh:write',
        'tiers:read', 'tiers:write'
    ]

    for permission_code in professional_user_permissions:
        op.execute(
            f"DELETE FROM role_permissions "
            f"WHERE role_id IN (SELECT id FROM roles WHERE code = 'PROFESSIONAL_USER') "
            f"AND permission_id IN (SELECT id FROM permissions WHERE code = '{permission_code}')"
        )

    # Remove ENTERPRISE_USER module-based permissions
    enterprise_user_permissions = [
        'transport:read', 'transport:write', 'transport:delete',
        'finance:read', 'finance:write', 'finance:delete', 'finance:validate',
        'parc:read', 'parc:write', 'parc:delete', 'parc:gate',
        'purchase:read', 'purchase:write', 'purchase:create', 'purchase:update', 'purchase:delete', 'purchase:submit', 'purchase:approve',
        'notifications:read_all', 'notifications:create',
        'rh:read', 'rh:write',
        'tiers:read', 'tiers:write', 'tiers:delete'
    ]

    for permission_code in enterprise_user_permissions:
        op.execute(
            f"DELETE FROM role_permissions "
            f"WHERE role_id IN (SELECT id FROM roles WHERE code = 'ENTERPRISE_USER') "
            f"AND permission_id IN (SELECT id FROM permissions WHERE code = '{permission_code}')"
        )
    # ### end Alembic commands ###