"""add_plan_roles

Revision ID: add_plan_roles
Revises: add_plan_permissions
Create Date: 2026-07-18 03:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_plan_roles'
down_revision = 'add_plan_permissions'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Insert plan-based roles
    roles = [
        ('BASIC_USER', 'Basic User', 'Access to basic features', True),
        ('PROFESSIONAL_USER', 'Professional User', 'Access to professional features', True),
        ('ENTERPRISE_USER', 'Enterprise User', 'Access to enterprise features', True),
    ]

    for code, name, description, is_active in roles:
        op.execute(
            f"INSERT INTO roles (code, name, description, is_active) VALUES ('{code}', '{name}', '{description}', {str(is_active).upper()}) "
            f"ON CONFLICT (code) DO NOTHING"
        )

    # Assign permissions to roles
    # BASIC_USER permissions
    basic_permissions = [
        'feature:basic_article_management',
        'feature:basic_client_management',
        'feature:basic_supplier_management',
        'feature:basic_invoicing',
        'feature:basic_payments',
        'feature:basic_reporting',
    ]

    for permission_code in basic_permissions:
        op.execute(
            f"INSERT INTO role_permissions (role_id, permission_id) "
            f"SELECT r.id, p.id FROM roles r, permissions p "
            f"WHERE r.code = 'BASIC_USER' AND p.code = '{permission_code}' "
            f"ON CONFLICT DO NOTHING"
        )

    # PROFESSIONAL_USER permissions (includes BASIC + professional)
    professional_permissions = [
        'feature:basic_article_management',
        'feature:basic_client_management',
        'feature:basic_supplier_management',
        'feature:basic_invoicing',
        'feature:basic_payments',
        'feature:basic_reporting',
        'feature:advanced_analytics',
        'feature:multi_warehouse',
        'feature:advanced_procurement',
        'feature:api_access',
        'feature:basic_ai',
        'feature:priority_support',
    ]

    for permission_code in professional_permissions:
        op.execute(
            f"INSERT INTO role_permissions (role_id, permission_id) "
            f"SELECT r.id, p.id FROM roles r, permissions p "
            f"WHERE r.code = 'PROFESSIONAL_USER' AND p.code = '{permission_code}' "
            f"ON CONFLICT DO NOTHING"
        )

    # ENTERPRISE_USER permissions (includes ALL)
    enterprise_permissions = [
        'feature:basic_article_management',
        'feature:basic_client_management',
        'feature:basic_supplier_management',
        'feature:basic_invoicing',
        'feature:basic_payments',
        'feature:basic_reporting',
        'feature:advanced_analytics',
        'feature:multi_warehouse',
        'feature:advanced_procurement',
        'feature:api_access',
        'feature:basic_ai',
        'feature:priority_support',
        'feature:full_ai_suite',
        'feature:unlimited_resources',
        'feature:custom_integrations',
        'feature:dedicated_support',
        'feature:sla_guarantee',
        'feature:on_premise_option',
        'feature:advanced_customization',
        'feature:white_labeling',
    ]

    for permission_code in enterprise_permissions:
        op.execute(
            f"INSERT INTO role_permissions (role_id, permission_id) "
            f"SELECT r.id, p.id FROM roles r, permissions p "
            f"WHERE r.code = 'ENTERPRISE_USER' AND p.code = '{permission_code}' "
            f"ON CONFLICT DO NOTHING"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove role-permission associations for plan roles
    op.execute("DELETE FROM role_permissions WHERE role_id IN (SELECT id FROM roles WHERE code IN ('BASIC_USER', 'PROFESSIONAL_USER', 'ENTERPRISE_USER'))")

    # Remove plan-based roles
    op.execute("DELETE FROM roles WHERE code IN ('BASIC_USER', 'PROFESSIONAL_USER', 'ENTERPRISE_USER')")
    # ### end Alembic commands ###