"""Add fuel and workshop models

Revision ID: 3a9461e2fd78
Revises: 5f1f9590b2f3
Create Date: 2026-07-02 08:36:55.287413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a9461e2fd78'
down_revision = '5f1f9590b2f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("""
        CREATE TABLE IF NOT EXISTS reparations_atelier (
            id SERIAL PRIMARY KEY,
            reference VARCHAR(30) UNIQUE NOT NULL,
            camion_id INTEGER NOT NULL,
            type_intervention VARCHAR(50) NOT NULL,
            description VARCHAR(500) NOT NULL,
            statut VARCHAR(30) NOT NULL,
            cout_estime INTEGER,
            date_entree VARCHAR(50) NOT NULL,
            date_sortie_prevue VARCHAR(50),
            mecanicien_en_charge VARCHAR(100),
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            deleted_at TIMESTAMPTZ,
            is_deleted BOOLEAN NOT NULL DEFAULT false
        );
    """)
    op.execute("""
        CREATE TABLE IF NOT EXISTS tickets_carburant (
            id SERIAL PRIMARY KEY,
            camion_id INTEGER NOT NULL REFERENCES camions_flotte(id),
            chauffeur_id INTEGER NOT NULL REFERENCES chauffeurs(id),
            quantite_litres NUMERIC(8,2) NOT NULL,
            prix_unitaire NUMERIC(10,2) NOT NULL,
            montant_total NUMERIC(12,2) NOT NULL,
            date_plein VARCHAR(50) NOT NULL,
            kilometrage INTEGER NOT NULL,
            station_service VARCHAR(100),
            notes TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            deleted_at TIMESTAMPTZ,
            is_deleted BOOLEAN NOT NULL DEFAULT false
        );
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets_carburant')
    op.drop_table('reparations_atelier')
    # ### end Alembic commands ###
