"""init_schema

Revision ID: c60cbd8f1160
Revises: 19a931345e99
Create Date: 2026-07-01 14:19:26.865467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c60cbd8f1160'
down_revision = '19a931345e99'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
