"""add_epod_fields

Revision ID: 61387c8cd073
Revises: 28ed111f3db5
Create Date: 2026-07-02 22:06:23.885364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61387c8cd073'
down_revision = '28ed111f3db5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('missions_transport', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preuve_livraison_signature', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('nom_receptionnaire', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('date_livraison_reelle', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('missions_transport', schema=None) as batch_op:
        batch_op.drop_column('date_livraison_reelle')
        batch_op.drop_column('nom_receptionnaire')
        batch_op.drop_column('preuve_livraison_signature')

    # ### end Alembic commands ###
