"""add_dynamic_rbac

Revision ID: 19a931345e99
Revises: add_new_models
Create Date: 2026-07-01 01:23:03.815539

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '19a931345e99'
down_revision = 'add_new_models'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_article', sa.String(length=20), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('categorie', sa.Enum('ALIMENTAIRE', 'PHARMACEUTIQUE', 'MATIERES_PREMIERES', 'PRODUITS_FINIS', 'EMBALLAGES_PALETES', 'EQUIPEMENT', 'PIECES_DETACHEES', 'MOBILIER_BUREAU_INFORMATIQUE', 'PRODUITS_DANGEREUX', 'PRODUITS_LUXE_VALEUR', 'VRAC', 'HORS_GABARIT', name='categoriearticle'), nullable=True),
    sa.Column('unite_mesure', sa.Enum('UDB', 'KG', 'TONNE', 'M3', 'M2', 'UNITE', name='unitemesure'), nullable=True),
    sa.Column('poids_unitaire', sa.Float(), nullable=True),
    sa.Column('volume_unitaire', sa.Float(), nullable=True),
    sa.Column('est_actif', sa.Boolean(), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('date_modification', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_articles'))
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_articles_code_article'), ['code_article'], unique=True)
        batch_op.create_index(batch_op.f('ix_articles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_nom'), ['nom'], unique=False)

    op.create_table('camions_flotte',
    sa.Column('immatriculation', sa.String(length=20), nullable=False),
    sa.Column('type_vehicule', sa.Enum('BENNE_VRAC', 'PORTE_CONTENEUR', 'CITERNE', 'FRIGORIFIQUE', 'PLATEAU', name='typevehicule'), nullable=False),
    sa.Column('marque', sa.String(length=50), nullable=False),
    sa.Column('modele', sa.String(length=50), nullable=False),
    sa.Column('charge_utile_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('volume_reservoir_litres', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('conso_theorique_l_100', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('statut', sa.String(length=30), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_camions_flotte')),
    sa.UniqueConstraint('immatriculation', name=op.f('uq_camions_flotte_immatriculation'))
    )
    op.create_table('chauffeurs',
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('numero_permis', sa.String(length=50), nullable=False),
    sa.Column('categorie_permis', sa.String(length=10), nullable=False),
    sa.Column('telephone', sa.String(length=30), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chauffeurs')),
    sa.UniqueConstraint('numero_permis', name=op.f('uq_chauffeurs_numero_permis'))
    )
    op.create_table('clients_magasin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=True),
    sa.Column('raison_sociale', sa.String(length=200), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('pays', sa.String(length=100), nullable=True),
    sa.Column('numero_contribuable', sa.String(length=50), nullable=True),
    sa.Column('est_actif', sa.Boolean(), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('date_modification', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clients_magasin'))
    )
    with op.batch_alter_table('clients_magasin', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_magasin_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_clients_magasin_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_magasin_nom'), ['nom'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_magasin_raison_sociale'), ['raison_sociale'], unique=False)

    op.create_table('dossiers_operationnels',
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('statut', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dossiers_operationnels'))
    )
    with op.batch_alter_table('dossiers_operationnels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dossiers_operationnels_reference'), ['reference'], unique=True)

    op.create_table('incoterms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=5), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('est_actif', sa.Boolean(), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incoterms'))
    )
    with op.batch_alter_table('incoterms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incoterms_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_incoterms_id'), ['id'], unique=False)

    op.create_table('magasins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('pays', sa.String(length=100), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('est_actif', sa.Boolean(), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('date_modification', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_magasins'))
    )
    with op.batch_alter_table('magasins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_magasins_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_magasins_id'), ['id'], unique=False)

    op.create_table('operations_trace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_ot', sa.String(length=20), nullable=False),
    sa.Column('type_operation', sa.String(length=50), nullable=False),
    sa.Column('table_cible', sa.String(length=100), nullable=False),
    sa.Column('enregistrement_id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.Column('date_operation', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('est_annule', sa.Boolean(), nullable=True),
    sa.Column('date_annulation', sa.DateTime(timezone=True), nullable=True),
    sa.Column('annule_par', sa.String(length=100), nullable=True),
    sa.Column('donnees_operation', sa.String(length=5000), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operations_trace'))
    )
    with op.batch_alter_table('operations_trace', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operations_trace_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_operations_trace_numero_ot'), ['numero_ot'], unique=True)

    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions'))
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_permissions_id'), ['id'], unique=False)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_roles_id'), ['id'], unique=False)

    op.create_table('tiers',
    sa.Column('code_tiers', sa.String(length=20), nullable=False),
    sa.Column('raison_sociale', sa.String(length=200), nullable=False),
    sa.Column('niu', sa.String(length=20), nullable=False),
    sa.Column('rccm', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('telephone', sa.String(length=30), nullable=True),
    sa.Column('adresse', sa.Text(), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('pays', sa.String(length=50), nullable=False),
    sa.Column('statut', sa.Enum('ACTIF', 'BLOQUE', 'INACTIF', name='statuttiers'), nullable=False),
    sa.Column('autorise_transport', sa.Boolean(), nullable=False),
    sa.Column('autorise_transit', sa.Boolean(), nullable=False),
    sa.Column('autorise_acconage', sa.Boolean(), nullable=False),
    sa.Column('autorise_magasinage', sa.Boolean(), nullable=False),
    sa.Column('compte_syscohada', sa.String(length=20), nullable=True),
    sa.Column('limite_credit_xaf', sa.Numeric(precision=15, scale=0), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tiers')),
    sa.UniqueConstraint('code_tiers', name=op.f('uq_tiers_code_tiers')),
    sa.UniqueConstraint('niu', name=op.f('uq_tiers_niu'))
    )
    with op.batch_alter_table('tiers', schema=None) as batch_op:
        batch_op.create_index('ix_tiers_code', ['code_tiers'], unique=False)
        batch_op.create_index('ix_tiers_niu', ['niu'], unique=False)
        batch_op.create_index('ix_tiers_statut', ['statut'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_transaction', sa.String(length=10), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('interface', sa.String(length=100), nullable=False),
    sa.Column('role_requis', sa.String(length=50), nullable=True),
    sa.Column('est_actif', sa.Boolean(), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('date_modification', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions'))
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_code_transaction'), ['code_transaction'], unique=True)
        batch_op.create_index(batch_op.f('ix_transactions_id'), ['id'], unique=False)

    op.create_table('types_conteneur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('longueur', sa.String(length=10), nullable=True),
    sa.Column('type_conteneur', sa.String(length=50), nullable=True),
    sa.Column('est_actif', sa.Boolean(), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_types_conteneur'))
    )
    with op.batch_alter_table('types_conteneur', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_types_conteneur_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_types_conteneur_id'), ['id'], unique=False)

    op.create_table('zones_parc',
    sa.Column('code_zone', sa.String(length=20), nullable=False),
    sa.Column('nom_zone', sa.String(length=100), nullable=False),
    sa.Column('type_zone', sa.String(length=50), nullable=False),
    sa.Column('capacite_evp', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_zones_parc')),
    sa.UniqueConstraint('code_zone', name=op.f('uq_zones_parc_code_zone'))
    )
    op.create_table('commandes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_commande', sa.String(length=50), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('date_commande', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('date_livraison_souhaitee', sa.DateTime(timezone=True), nullable=True),
    sa.Column('statut', sa.Enum('EN_ATTENTE', 'VERROUILLEE', 'PAYEE', 'EN_PREPARATION', 'PRETE', 'LIVREE', 'ANNULEE', name='statutcommande'), nullable=True),
    sa.Column('est_verrouille', sa.Boolean(), nullable=True),
    sa.Column('paiement_valide', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('valide_par', sa.String(length=100), nullable=True),
    sa.Column('date_validation', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cree_par', sa.String(length=100), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('date_modification', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients_magasin.id'], name=op.f('fk_commandes_client_id_clients_magasin')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_commandes'))
    )
    with op.batch_alter_table('commandes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commandes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_commandes_numero_commande'), ['numero_commande'], unique=True)

    op.create_table('declarations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_bl', sa.String(length=50), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('incoterm_id', sa.Integer(), nullable=True),
    sa.Column('type_conteneur_id', sa.Integer(), nullable=True),
    sa.Column('numero_conteneur', sa.String(length=50), nullable=True),
    sa.Column('date_declaration', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('date_arrivee_prevue', sa.DateTime(timezone=True), nullable=True),
    sa.Column('statut', sa.Enum('BROUILLON', 'VALIDEE', 'ANNULEE', name='statutdeclaration'), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('cree_par', sa.String(length=100), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('date_modification', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients_magasin.id'], name=op.f('fk_declarations_client_id_clients_magasin')),
    sa.ForeignKeyConstraint(['incoterm_id'], ['incoterms.id'], name=op.f('fk_declarations_incoterm_id_incoterms')),
    sa.ForeignKeyConstraint(['type_conteneur_id'], ['types_conteneur.id'], name=op.f('fk_declarations_type_conteneur_id_types_conteneur')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_declarations'))
    )
    with op.batch_alter_table('declarations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_declarations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_declarations_numero_bl'), ['numero_bl'], unique=True)

    op.create_table('emplacements_parc',
    sa.Column('code_emplacement', sa.String(length=30), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('rangee', sa.String(length=10), nullable=False),
    sa.Column('bay', sa.Integer(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('statut', sa.Enum('LIBRE', 'OCCUPE', 'RESERVE', 'MAINTENANCE', name='statutemplacement'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones_parc.id'], name=op.f('fk_emplacements_parc_zone_id_zones_parc')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emplacements_parc')),
    sa.UniqueConstraint('code_emplacement', name=op.f('uq_emplacements_parc_code_emplacement'))
    )
    with op.batch_alter_table('emplacements_parc', schema=None) as batch_op:
        batch_op.create_index('ix_emplacements_statut', ['statut'], unique=False)
        batch_op.create_index('ix_emplacements_zone', ['zone_id'], unique=False)

    op.create_table('grilles_tarifaires',
    sa.Column('code_tarif', sa.String(length=20), nullable=False),
    sa.Column('tiers_id', sa.Integer(), nullable=True),
    sa.Column('service', sa.String(length=50), nullable=False),
    sa.Column('type_marchandise', sa.String(length=50), nullable=False),
    sa.Column('tarif_unitaire_xaf', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('unite', sa.String(length=20), nullable=False),
    sa.Column('date_debut_validite', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_fin_validite', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tiers_id'], ['tiers.id'], name=op.f('fk_grilles_tarifaires_tiers_id_tiers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grilles_tarifaires')),
    sa.UniqueConstraint('code_tarif', name=op.f('uq_grilles_tarifaires_code_tarif'))
    )
    op.create_table('lignes_goods_declaration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('declaration_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('quantite_declaree', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('unite_mesure', sa.String(length=20), nullable=False),
    sa.Column('poids_kg', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('valeur_unitaire_xaf', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('valeur_totale_xaf', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_lignes_goods_declaration_article_id_articles')),
    sa.ForeignKeyConstraint(['declaration_id'], ['goods_declarations.id'], name=op.f('fk_lignes_goods_declaration_declaration_id_goods_declarations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lignes_goods_declaration'))
    )
    with op.batch_alter_table('lignes_goods_declaration', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lignes_goods_declaration_id'), ['id'], unique=False)

    op.create_table('missions_transport',
    sa.Column('reference', sa.String(length=30), nullable=False),
    sa.Column('tiers_id', sa.Integer(), nullable=False),
    sa.Column('camion_id', sa.Integer(), nullable=False),
    sa.Column('chauffeur_id', sa.Integer(), nullable=False),
    sa.Column('dossier_id', sa.Integer(), nullable=True),
    sa.Column('origine', sa.String(length=200), nullable=False),
    sa.Column('destination', sa.String(length=200), nullable=False),
    sa.Column('distance_km', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('type_marchandise', sa.String(length=50), nullable=False),
    sa.Column('poids_kg', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('statut', sa.Enum('PLANIFIE', 'EN_CHARGEMENT', 'EN_ROUTE', 'EN_LIVRAISON', 'LIVRE', 'CLOTURE', name='statutmission'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['camion_id'], ['camions_flotte.id'], name=op.f('fk_missions_transport_camion_id_camions_flotte')),
    sa.ForeignKeyConstraint(['chauffeur_id'], ['chauffeurs.id'], name=op.f('fk_missions_transport_chauffeur_id_chauffeurs')),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers_operationnels.id'], name=op.f('fk_missions_transport_dossier_id_dossiers_operationnels')),
    sa.ForeignKeyConstraint(['tiers_id'], ['tiers.id'], name=op.f('fk_missions_transport_tiers_id_tiers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_missions_transport')),
    sa.UniqueConstraint('reference', name=op.f('uq_missions_transport_reference'))
    )
    with op.batch_alter_table('missions_transport', schema=None) as batch_op:
        batch_op.create_index('ix_missions_statut', ['statut'], unique=False)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('magasin_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('quantite_disponible', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('quantite_udb', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('statut', sa.Enum('NORMAL', 'DECHIRE', 'MOUILLE', 'ENDOMMAGE', 'PERIME', 'EN_ATTENTE', 'RESERVE', name='statutstock'), nullable=True),
    sa.Column('derniere_maj', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_stocks_article_id_articles')),
    sa.ForeignKeyConstraint(['magasin_id'], ['magasins.id'], name=op.f('fk_stocks_magasin_id_magasins')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stocks')),
    sa.UniqueConstraint('magasin_id', 'article_id', name='uq_stock_magasin_article')
    )
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stocks_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('agency_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.String(length=255), nullable=True),
    sa.Column('mfa_backup_codes', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], name=op.f('fk_users_agency_id_agencies')),
    sa.ForeignKeyConstraint(['role'], ['roles.code'], name=op.f('fk_users_role_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('audit_log',
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('agency_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], name=op.f('fk_audit_log_agency_id_agencies')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_log_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_table('bandes_livraison',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_bande', sa.String(length=50), nullable=False),
    sa.Column('commande_id', sa.Integer(), nullable=False),
    sa.Column('magasin_id', sa.Integer(), nullable=False),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('date_livraison', sa.DateTime(timezone=True), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('nombre_camions', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('prepare_par', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['commande_id'], ['commandes.id'], name=op.f('fk_bandes_livraison_commande_id_commandes')),
    sa.ForeignKeyConstraint(['magasin_id'], ['magasins.id'], name=op.f('fk_bandes_livraison_magasin_id_magasins')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bandes_livraison'))
    )
    with op.batch_alter_table('bandes_livraison', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bandes_livraison_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bandes_livraison_numero_bande'), ['numero_bande'], unique=True)

    op.create_table('factures',
    sa.Column('numero_facture', sa.String(length=30), nullable=False),
    sa.Column('tiers_id', sa.Integer(), nullable=False),
    sa.Column('dossier_id', sa.Integer(), nullable=True),
    sa.Column('mission_id', sa.Integer(), nullable=True),
    sa.Column('montant_ht_xaf', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tva_xaf', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('montant_ttc_xaf', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('date_emission', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_echeance', sa.DateTime(timezone=True), nullable=False),
    sa.Column('statut', sa.Enum('BROUILLON', 'EMISE', 'PARTIELLEMENT_PAYEE', 'PAYEE', 'ANNULEE', name='statutfacture'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers_operationnels.id'], name=op.f('fk_factures_dossier_id_dossiers_operationnels')),
    sa.ForeignKeyConstraint(['mission_id'], ['missions_transport.id'], name=op.f('fk_factures_mission_id_missions_transport')),
    sa.ForeignKeyConstraint(['tiers_id'], ['tiers.id'], name=op.f('fk_factures_tiers_id_tiers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_factures')),
    sa.UniqueConstraint('numero_facture', name=op.f('uq_factures_numero_facture'))
    )
    with op.batch_alter_table('factures', schema=None) as batch_op:
        batch_op.create_index('ix_factures_statut', ['statut'], unique=False)
        batch_op.create_index('ix_factures_tiers', ['tiers_id'], unique=False)

    op.create_table('idempotency_keys',
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agency_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_status_code', sa.Integer(), nullable=False),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('response_headers', sa.Text(), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('date_expiration', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], name=op.f('fk_idempotency_keys_agency_id_agencies')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_idempotency_keys_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idempotency_keys'))
    )
    with op.batch_alter_table('idempotency_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idempotency_keys_idempotency_key'), ['idempotency_key'], unique=False)

    op.create_table('lignes_commande',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commande_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('quantite_demandee', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('quantite_livree', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('unite_mesure', sa.Enum('UDB', 'KG', 'TONNE', 'M3', 'M2', 'UNITE', name='unitemesure'), nullable=False),
    sa.Column('prix_unitaire', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_lignes_commande_article_id_articles')),
    sa.ForeignKeyConstraint(['commande_id'], ['commandes.id'], name=op.f('fk_lignes_commande_commande_id_commandes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lignes_commande'))
    )
    with op.batch_alter_table('lignes_commande', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lignes_commande_id'), ['id'], unique=False)

    op.create_table('lignes_declaration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('declaration_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('quantite_declaree', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('unite_mesure', sa.Enum('UDB', 'KG', 'TONNE', 'M3', 'M2', 'UNITE', name='unitemesure'), nullable=False),
    sa.Column('quantite_udb', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_lignes_declaration_article_id_articles')),
    sa.ForeignKeyConstraint(['declaration_id'], ['declarations.id'], name=op.f('fk_lignes_declaration_declaration_id_declarations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lignes_declaration'))
    )
    with op.batch_alter_table('lignes_declaration', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lignes_declaration_id'), ['id'], unique=False)

    op.create_table('notifications',
    sa.Column('type_notification', sa.String(length=50), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('priorite', sa.String(length=20), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('destinataire_id', sa.Integer(), nullable=False),
    sa.Column('expediteur_id', sa.Integer(), nullable=True),
    sa.Column('agency_id', sa.Integer(), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('contexte', sa.JSON(), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('date_lecture', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_archivage', sa.DateTime(timezone=True), nullable=True),
    sa.Column('canal_envoye', sa.String(length=100), nullable=True),
    sa.Column('date_envoi', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tentatives_envoi', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], name=op.f('fk_notifications_agency_id_agencies')),
    sa.ForeignKeyConstraint(['destinataire_id'], ['users.id'], name=op.f('fk_notifications_destinataire_id_users')),
    sa.ForeignKeyConstraint(['expediteur_id'], ['users.id'], name=op.f('fk_notifications_expediteur_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_table('receptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_reception', sa.String(length=50), nullable=False),
    sa.Column('declaration_id', sa.Integer(), nullable=False),
    sa.Column('magasin_id', sa.Integer(), nullable=False),
    sa.Column('date_reception', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('statut', sa.Enum('EN_COURS', 'COMPLETEE', 'ANNULEE', name='statutreception'), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('recu_par', sa.String(length=100), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('date_modification', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['declaration_id'], ['declarations.id'], name=op.f('fk_receptions_declaration_id_declarations')),
    sa.ForeignKeyConstraint(['magasin_id'], ['magasins.id'], name=op.f('fk_receptions_magasin_id_magasins')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_receptions'))
    )
    with op.batch_alter_table('receptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receptions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_receptions_numero_reception'), ['numero_reception'], unique=True)

    op.create_table('stock_physique_parc',
    sa.Column('numero_conteneur', sa.String(length=20), nullable=False),
    sa.Column('emplacement_id', sa.Integer(), nullable=False),
    sa.Column('type_conteneur', sa.String(length=20), nullable=False),
    sa.Column('etat', sa.String(length=20), nullable=False),
    sa.Column('poids_tare_kg', sa.Integer(), nullable=True),
    sa.Column('date_gate_in', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_gate_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['emplacement_id'], ['emplacements_parc.id'], name=op.f('fk_stock_physique_parc_emplacement_id_emplacements_parc')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_physique_parc')),
    sa.UniqueConstraint('numero_conteneur', name=op.f('uq_stock_physique_parc_numero_conteneur'))
    )
    op.create_table('avoirs',
    sa.Column('numero_avoir', sa.String(length=50), nullable=False),
    sa.Column('facture_origine_id', sa.Integer(), nullable=True),
    sa.Column('tiers_id', sa.Integer(), nullable=False),
    sa.Column('montant_xaf', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('motif', sa.String(length=500), nullable=False),
    sa.Column('est_utilise', sa.Boolean(), nullable=False),
    sa.Column('cree_par', sa.String(length=100), nullable=True),
    sa.Column('date_emission', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['facture_origine_id'], ['factures.id'], name=op.f('fk_avoirs_facture_origine_id_factures')),
    sa.ForeignKeyConstraint(['tiers_id'], ['tiers.id'], name=op.f('fk_avoirs_tiers_id_tiers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_avoirs')),
    sa.UniqueConstraint('numero_avoir', name=op.f('uq_avoirs_numero_avoir'))
    )
    op.create_table('encaissements',
    sa.Column('reference', sa.String(length=30), nullable=False),
    sa.Column('tiers_id', sa.Integer(), nullable=False),
    sa.Column('facture_id', sa.Integer(), nullable=True),
    sa.Column('montant_xaf', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('mode_paiement', sa.String(length=50), nullable=False),
    sa.Column('date_paiement', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reference_paiement', sa.String(length=100), nullable=True),
    sa.Column('lettree', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['facture_id'], ['factures.id'], name=op.f('fk_encaissements_facture_id_factures')),
    sa.ForeignKeyConstraint(['tiers_id'], ['tiers.id'], name=op.f('fk_encaissements_tiers_id_tiers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_encaissements')),
    sa.UniqueConstraint('reference', name=op.f('uq_encaissements_reference'))
    )
    op.create_table('lignes_bande_livraison',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bande_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('quantite', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('unite_mesure', sa.Enum('UDB', 'KG', 'TONNE', 'M3', 'M2', 'UNITE', name='unitemesure'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_lignes_bande_livraison_article_id_articles')),
    sa.ForeignKeyConstraint(['bande_id'], ['bandes_livraison.id'], name=op.f('fk_lignes_bande_livraison_bande_id_bandes_livraison')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lignes_bande_livraison'))
    )
    with op.batch_alter_table('lignes_bande_livraison', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lignes_bande_livraison_id'), ['id'], unique=False)

    op.create_table('lignes_reception',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reception_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('quantite_recue', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('unite_mesure', sa.Enum('UDB', 'KG', 'TONNE', 'M3', 'M2', 'UNITE', name='unitemesure'), nullable=False),
    sa.Column('quantite_udb', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_lignes_reception_article_id_articles')),
    sa.ForeignKeyConstraint(['reception_id'], ['receptions.id'], name=op.f('fk_lignes_reception_reception_id_receptions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lignes_reception'))
    )
    with op.batch_alter_table('lignes_reception', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lignes_reception_id'), ['id'], unique=False)

    op.create_table('mouvements_parc',
    sa.Column('reference', sa.String(length=30), nullable=False),
    sa.Column('conteneur_id', sa.Integer(), nullable=False),
    sa.Column('type_mouvement', sa.String(length=20), nullable=False),
    sa.Column('emplacement_source_id', sa.Integer(), nullable=True),
    sa.Column('emplacement_dest_id', sa.Integer(), nullable=True),
    sa.Column('date_mouvement', sa.DateTime(timezone=True), nullable=False),
    sa.Column('operateur_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conteneur_id'], ['stock_physique_parc.id'], name=op.f('fk_mouvements_parc_conteneur_id_stock_physique_parc')),
    sa.ForeignKeyConstraint(['emplacement_dest_id'], ['emplacements_parc.id'], name=op.f('fk_mouvements_parc_emplacement_dest_id_emplacements_parc')),
    sa.ForeignKeyConstraint(['emplacement_source_id'], ['emplacements_parc.id'], name=op.f('fk_mouvements_parc_emplacement_source_id_emplacements_parc')),
    sa.ForeignKeyConstraint(['operateur_id'], ['users.id'], name=op.f('fk_mouvements_parc_operateur_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mouvements_parc')),
    sa.UniqueConstraint('reference', name=op.f('uq_mouvements_parc_reference'))
    )
    op.create_table('notifications_destinations',
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('destinataire_id', sa.Integer(), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('date_lecture', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['destinataire_id'], ['users.id'], name=op.f('fk_notifications_destinations_destinataire_id_users')),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], name=op.f('fk_notifications_destinations_notification_id_notifications')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications_destinations'))
    )
    with op.batch_alter_table('goods_declaration_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goods_declaration_lines_declaration_id'))
        batch_op.drop_index(batch_op.f('ix_goods_declaration_lines_id'))

    op.drop_table('goods_declaration_lines')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_table_name'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('agencies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('pays',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('date_creation',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
        batch_op.drop_index(batch_op.f('ix_agencies_id'))

    with op.batch_alter_table('commande_factures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.drop_column('date_modification')

    with op.batch_alter_table('commande_livraisons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.drop_column('date_modification')

    with op.batch_alter_table('facture_paiements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_facture_paiements_paiement_id_encaissements'), 'encaissements', ['paiement_id'], ['id'])
        batch_op.drop_column('date_modification')

    with op.batch_alter_table('goods_declarations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code_article', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('code_transit', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('poids_kg', sa.Numeric(precision=15, scale=3), nullable=True))
        batch_op.add_column(sa.Column('valeur_xaf', sa.Numeric(precision=15, scale=2), nullable=True))
        batch_op.add_column(sa.Column('origine', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('destination', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('numero_conteneur', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('observations', sa.Text(), nullable=True))
        batch_op.alter_column('quantite',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=15, scale=3),
               existing_nullable=False)
        batch_op.alter_column('statut',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('BROUILLON', 'VALIDEE', 'ANNULEE', 'EN_TRANSIT', 'ARRIVEE', name='statutgoodsdeclaration'),
               nullable=True)
        batch_op.alter_column('cree_par',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('date_creation',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_goods_declarations_article_id'))
        batch_op.drop_index(batch_op.f('ix_goods_declarations_statut'))
        batch_op.create_index(batch_op.f('ix_goods_declarations_code_article'), ['code_article'], unique=False)
        batch_op.create_index(batch_op.f('ix_goods_declarations_code_transit'), ['code_transit'], unique=False)
        batch_op.drop_column('declaration_douaniere')
        batch_op.drop_column('devise')
        batch_op.drop_column('date_declaration')
        batch_op.drop_column('port_depart')
        batch_op.drop_column('article_id')
        batch_op.drop_column('incoterm')
        batch_op.drop_column('poids')
        batch_op.drop_column('valeur')
        batch_op.drop_column('port_arrivee')

    with op.batch_alter_table('mission_factures', schema=None, reflect_kwargs={'resolve_fks': False}) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_mission_factures_mission_id_missions'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_mission_factures_mission_id_missions_transport'), 'missions_transport', ['mission_id'], ['id'])
        batch_op.drop_column('date_modification')

    with op.batch_alter_table('passerelles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.drop_column('date_modification')

    with op.batch_alter_table('reception_stocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.drop_column('date_modification')

    with op.batch_alter_table('receptions_mag3', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_reception', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('cree_par', sa.String(length=100), nullable=True))
        batch_op.alter_column('magasin_source',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.alter_column('magasin_destination',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('quantite_attendue',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=15, scale=3),
               existing_nullable=False)
        batch_op.alter_column('quantite_recue',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=15, scale=3),
               existing_nullable=False)
        batch_op.alter_column('declaration_douaniere',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('recu_par',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('statut',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('date_creation',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_receptions_mag3_article_id'))
        batch_op.drop_index(batch_op.f('ix_receptions_mag3_date_reception'))
        batch_op.drop_index(batch_op.f('ix_receptions_mag3_removal_slip_id'))
        batch_op.drop_index(batch_op.f('ix_receptions_mag3_statut'))
        batch_op.create_index(batch_op.f('ix_receptions_mag3_numero_reception'), ['numero_reception'], unique=True)
        batch_op.create_foreign_key(batch_op.f('fk_receptions_mag3_removal_slip_id_removal_slips'), 'removal_slips', ['removal_slip_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_receptions_mag3_article_id_articles'), 'articles', ['article_id'], ['id'])
        batch_op.drop_column('date_validation')
        batch_op.drop_column('valide_par')

    with op.batch_alter_table('removal_slips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motif', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('observations', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cree_par', sa.String(length=100), nullable=True))
        batch_op.alter_column('magasin_source',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('magasin_destination',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('quantite',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=15, scale=3),
               existing_nullable=False)
        batch_op.alter_column('declaration_douaniere',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('statut',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('date_creation',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_removal_slips_article_id'))
        batch_op.drop_index(batch_op.f('ix_removal_slips_magasin_destination'))
        batch_op.drop_index(batch_op.f('ix_removal_slips_magasin_source'))
        batch_op.drop_index(batch_op.f('ix_removal_slips_statut'))
        batch_op.create_foreign_key(batch_op.f('fk_removal_slips_article_id_articles'), 'articles', ['article_id'], ['id'])
        batch_op.drop_column('demande_par')

    with op.batch_alter_table('supplier_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categorie_fournisseur', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('delai_moyen_livraison', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('qualite_service', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('date_evaluation', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('cree_par', sa.String(length=100), nullable=True))
        batch_op.alter_column('date_creation',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_supplier_profiles_supplier_id'))
        batch_op.drop_column('telephone_contact')
        batch_op.drop_column('delai_paiement_jours')
        batch_op.drop_column('actif')
        batch_op.drop_column('contact_principal')
        batch_op.drop_column('remise_pourcentage')
        batch_op.drop_column('conditions_paiement')
        batch_op.drop_column('email_contact')

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acronyme', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('type_entite', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('rccm', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('id_fiscal', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('boite_postale', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('region', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('conditions_paiement', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('devise', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('compte_bancaire', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('nom_banque', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('est_actif', sa.Boolean(), nullable=True))
        batch_op.alter_column('niu',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('telephone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)
        batch_op.alter_column('limite_credit_xaf',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=True)
        batch_op.alter_column('categorie',
               existing_type=sa.VARCHAR(length=13),
               type_=sa.Enum('TRANSPORT', 'ACQUISITION', 'SERVICE', 'EQUIPEMENT', 'FOURNITURE', name='categoriesupplier'),
               nullable=True)
        batch_op.alter_column('statut',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('ACTIF', 'BLOQUE', 'INACTIF', 'EN_VALIDATION', name='statutsupplier'),
               nullable=True)
        batch_op.alter_column('cree_par',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('date_creation',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_suppliers_categorie'))
        batch_op.drop_index(batch_op.f('ix_suppliers_statut'))
        batch_op.create_index(batch_op.f('ix_suppliers_raison_sociale'), ['raison_sociale'], unique=False)
        batch_op.drop_column('solde_credit_xaf')
        batch_op.drop_column('site_web')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_web', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('solde_credit_xaf', sa.INTEGER(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_suppliers_raison_sociale'))
        batch_op.create_index(batch_op.f('ix_suppliers_statut'), ['statut'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppliers_categorie'), ['categorie'], unique=False)
        batch_op.alter_column('date_creation',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('cree_par',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('statut',
               existing_type=sa.Enum('ACTIF', 'BLOQUE', 'INACTIF', 'EN_VALIDATION', name='statutsupplier'),
               type_=sa.VARCHAR(length=7),
               nullable=False)
        batch_op.alter_column('categorie',
               existing_type=sa.Enum('TRANSPORT', 'ACQUISITION', 'SERVICE', 'EQUIPEMENT', 'FOURNITURE', name='categoriesupplier'),
               type_=sa.VARCHAR(length=13),
               nullable=False)
        batch_op.alter_column('limite_credit_xaf',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('telephone',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('niu',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('est_actif')
        batch_op.drop_column('nom_banque')
        batch_op.drop_column('compte_bancaire')
        batch_op.drop_column('devise')
        batch_op.drop_column('conditions_paiement')
        batch_op.drop_column('region')
        batch_op.drop_column('boite_postale')
        batch_op.drop_column('id_fiscal')
        batch_op.drop_column('rccm')
        batch_op.drop_column('type_entite')
        batch_op.drop_column('acronyme')

    with op.batch_alter_table('supplier_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_contact', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('conditions_paiement', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('remise_pourcentage', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('contact_principal', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('actif', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('delai_paiement_jours', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('telephone_contact', sa.VARCHAR(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_supplier_profiles_supplier_id'), ['supplier_id'], unique=False)
        batch_op.alter_column('date_creation',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_column('cree_par')
        batch_op.drop_column('date_evaluation')
        batch_op.drop_column('qualite_service')
        batch_op.drop_column('delai_moyen_livraison')
        batch_op.drop_column('categorie_fournisseur')

    with op.batch_alter_table('removal_slips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('demande_par', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_removal_slips_article_id_articles'), type_='foreignkey')
        batch_op.create_index(batch_op.f('ix_removal_slips_statut'), ['statut'], unique=False)
        batch_op.create_index(batch_op.f('ix_removal_slips_magasin_source'), ['magasin_source'], unique=False)
        batch_op.create_index(batch_op.f('ix_removal_slips_magasin_destination'), ['magasin_destination'], unique=False)
        batch_op.create_index(batch_op.f('ix_removal_slips_article_id'), ['article_id'], unique=False)
        batch_op.alter_column('date_creation',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('statut',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('declaration_douaniere',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('quantite',
               existing_type=sa.Numeric(precision=15, scale=3),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('magasin_destination',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('magasin_source',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('cree_par')
        batch_op.drop_column('observations')
        batch_op.drop_column('motif')

    with op.batch_alter_table('receptions_mag3', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valide_par', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('date_validation', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_receptions_mag3_article_id_articles'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_receptions_mag3_removal_slip_id_removal_slips'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_receptions_mag3_numero_reception'))
        batch_op.create_index(batch_op.f('ix_receptions_mag3_statut'), ['statut'], unique=False)
        batch_op.create_index(batch_op.f('ix_receptions_mag3_removal_slip_id'), ['removal_slip_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_receptions_mag3_date_reception'), ['date_reception'], unique=False)
        batch_op.create_index(batch_op.f('ix_receptions_mag3_article_id'), ['article_id'], unique=False)
        batch_op.alter_column('date_creation',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('statut',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('recu_par',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('declaration_douaniere',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('quantite_recue',
               existing_type=sa.Numeric(precision=15, scale=3),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('quantite_attendue',
               existing_type=sa.Numeric(precision=15, scale=3),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('magasin_destination',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('magasin_source',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('cree_par')
        batch_op.drop_column('numero_reception')

    with op.batch_alter_table('reception_stocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_modification', sa.DATETIME(), nullable=True))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('passerelles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_modification', sa.DATETIME(), nullable=True))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('mission_factures', schema=None, reflect_kwargs={'resolve_fks': False}) as batch_op:
        batch_op.add_column(sa.Column('date_modification', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_mission_factures_mission_id_missions_transport'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_mission_factures_mission_id_missions'), 'missions', ['mission_id'], ['id'])
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('goods_declarations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('port_arrivee', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('valeur', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('poids', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('incoterm', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('article_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('port_depart', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('date_declaration', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('devise', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('declaration_douaniere', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_index(batch_op.f('ix_goods_declarations_code_transit'))
        batch_op.drop_index(batch_op.f('ix_goods_declarations_code_article'))
        batch_op.create_index(batch_op.f('ix_goods_declarations_statut'), ['statut'], unique=False)
        batch_op.create_index(batch_op.f('ix_goods_declarations_article_id'), ['article_id'], unique=False)
        batch_op.alter_column('date_creation',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('cree_par',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('statut',
               existing_type=sa.Enum('BROUILLON', 'VALIDEE', 'ANNULEE', 'EN_TRANSIT', 'ARRIVEE', name='statutgoodsdeclaration'),
               type_=sa.VARCHAR(length=9),
               nullable=False)
        batch_op.alter_column('quantite',
               existing_type=sa.Numeric(precision=15, scale=3),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('observations')
        batch_op.drop_column('numero_conteneur')
        batch_op.drop_column('destination')
        batch_op.drop_column('origine')
        batch_op.drop_column('valeur_xaf')
        batch_op.drop_column('poids_kg')
        batch_op.drop_column('description')
        batch_op.drop_column('code_transit')
        batch_op.drop_column('code_article')

    with op.batch_alter_table('facture_paiements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_modification', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_facture_paiements_paiement_id_encaissements'), type_='foreignkey')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('commande_livraisons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_modification', sa.DATETIME(), nullable=True))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('commande_factures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_modification', sa.DATETIME(), nullable=True))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('agencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agencies_id'), ['id'], unique=False)
        batch_op.alter_column('date_creation',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('pays',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    op.create_table('audit_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('agency_id', sa.INTEGER(), nullable=True),
    sa.Column('action', sa.VARCHAR(length=50), nullable=False),
    sa.Column('table_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('record_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('old_values', sqlite.JSON(), nullable=True),
    sa.Column('new_values', sqlite.JSON(), nullable=True),
    sa.Column('context', sqlite.JSON(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=500), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_table_name'), ['table_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)

    op.create_table('goods_declaration_lines',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('declaration_id', sa.INTEGER(), nullable=False),
    sa.Column('article_id', sa.INTEGER(), nullable=False),
    sa.Column('quantite', sa.INTEGER(), nullable=False),
    sa.Column('unite', sa.VARCHAR(length=20), nullable=False),
    sa.Column('poids', sa.FLOAT(), nullable=True),
    sa.Column('valeur', sa.FLOAT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('date_creation', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_goods_declaration_lines_article_id_articles')),
    sa.ForeignKeyConstraint(['declaration_id'], ['goods_declarations.id'], name=op.f('fk_goods_declaration_lines_declaration_id_goods_declarations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goods_declaration_lines'))
    )
    with op.batch_alter_table('goods_declaration_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goods_declaration_lines_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goods_declaration_lines_declaration_id'), ['declaration_id'], unique=False)

    op.drop_table('notifications_destinations')
    op.drop_table('mouvements_parc')
    with op.batch_alter_table('lignes_reception', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lignes_reception_id'))

    op.drop_table('lignes_reception')
    with op.batch_alter_table('lignes_bande_livraison', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lignes_bande_livraison_id'))

    op.drop_table('lignes_bande_livraison')
    op.drop_table('encaissements')
    op.drop_table('avoirs')
    op.drop_table('stock_physique_parc')
    with op.batch_alter_table('receptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receptions_numero_reception'))
        batch_op.drop_index(batch_op.f('ix_receptions_id'))

    op.drop_table('receptions')
    op.drop_table('notifications')
    with op.batch_alter_table('lignes_declaration', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lignes_declaration_id'))

    op.drop_table('lignes_declaration')
    with op.batch_alter_table('lignes_commande', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lignes_commande_id'))

    op.drop_table('lignes_commande')
    with op.batch_alter_table('idempotency_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idempotency_keys_idempotency_key'))

    op.drop_table('idempotency_keys')
    with op.batch_alter_table('factures', schema=None) as batch_op:
        batch_op.drop_index('ix_factures_tiers')
        batch_op.drop_index('ix_factures_statut')

    op.drop_table('factures')
    with op.batch_alter_table('bandes_livraison', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bandes_livraison_numero_bande'))
        batch_op.drop_index(batch_op.f('ix_bandes_livraison_id'))

    op.drop_table('bandes_livraison')
    op.drop_table('audit_log')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stocks_id'))

    op.drop_table('stocks')
    op.drop_table('role_permissions')
    with op.batch_alter_table('missions_transport', schema=None) as batch_op:
        batch_op.drop_index('ix_missions_statut')

    op.drop_table('missions_transport')
    with op.batch_alter_table('lignes_goods_declaration', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lignes_goods_declaration_id'))

    op.drop_table('lignes_goods_declaration')
    op.drop_table('grilles_tarifaires')
    with op.batch_alter_table('emplacements_parc', schema=None) as batch_op:
        batch_op.drop_index('ix_emplacements_zone')
        batch_op.drop_index('ix_emplacements_statut')

    op.drop_table('emplacements_parc')
    with op.batch_alter_table('declarations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_declarations_numero_bl'))
        batch_op.drop_index(batch_op.f('ix_declarations_id'))

    op.drop_table('declarations')
    with op.batch_alter_table('commandes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commandes_numero_commande'))
        batch_op.drop_index(batch_op.f('ix_commandes_id'))

    op.drop_table('commandes')
    op.drop_table('zones_parc')
    with op.batch_alter_table('types_conteneur', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_types_conteneur_id'))
        batch_op.drop_index(batch_op.f('ix_types_conteneur_code'))

    op.drop_table('types_conteneur')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_code_transaction'))

    op.drop_table('transactions')
    with op.batch_alter_table('tiers', schema=None) as batch_op:
        batch_op.drop_index('ix_tiers_statut')
        batch_op.drop_index('ix_tiers_niu')
        batch_op.drop_index('ix_tiers_code')

    op.drop_table('tiers')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_id'))
        batch_op.drop_index(batch_op.f('ix_roles_code'))

    op.drop_table('roles')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_id'))
        batch_op.drop_index(batch_op.f('ix_permissions_code'))

    op.drop_table('permissions')
    with op.batch_alter_table('operations_trace', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operations_trace_numero_ot'))
        batch_op.drop_index(batch_op.f('ix_operations_trace_id'))

    op.drop_table('operations_trace')
    with op.batch_alter_table('magasins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_magasins_id'))
        batch_op.drop_index(batch_op.f('ix_magasins_code'))

    op.drop_table('magasins')
    with op.batch_alter_table('incoterms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incoterms_id'))
        batch_op.drop_index(batch_op.f('ix_incoterms_code'))

    op.drop_table('incoterms')
    with op.batch_alter_table('dossiers_operationnels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dossiers_operationnels_reference'))

    op.drop_table('dossiers_operationnels')
    with op.batch_alter_table('clients_magasin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_magasin_raison_sociale'))
        batch_op.drop_index(batch_op.f('ix_clients_magasin_nom'))
        batch_op.drop_index(batch_op.f('ix_clients_magasin_id'))
        batch_op.drop_index(batch_op.f('ix_clients_magasin_code'))

    op.drop_table('clients_magasin')
    op.drop_table('chauffeurs')
    op.drop_table('camions_flotte')
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_nom'))
        batch_op.drop_index(batch_op.f('ix_articles_id'))
        batch_op.drop_index(batch_op.f('ix_articles_code_article'))

    op.drop_table('articles')
    # ### end Alembic commands ###
