// src/app/(auth)/mfa/page.tsx
// 100% fidèle à ERP/mfa_verification/code.html
// Layout: carte centrée avec TopBar + champs code 6 chiffres
'use client'

import { useState, useRef, useEffect, KeyboardEvent, ClipboardEvent, ChangeEvent } from 'react'
import { useRouter } from 'next/navigation'

export default function MfaPage() {
  const router = useRouter()
  const [code, setCode] = useState<string[]>(Array(6).fill(''))
  const [isLoading, setIsLoading] = useState(false)
  const [showSetup, setShowSetup] = useState(false)
  const inputRefs = useRef<(HTMLInputElement | null)[]>([])

  // Auto-focus first input on mount
  useEffect(() => {
    inputRefs.current[0]?.focus()
  }, [])

  const handleChange = (index: number, e: ChangeEvent<HTMLInputElement>) => {
    const value = e.target.value
    if (!/^\d*$/.test(value)) return

    const newCode = [...code]
    newCode[index] = value.slice(-1)
    setCode(newCode)

    // Auto-advance to next input
    if (value && index < 5) {
      inputRefs.current[index + 1]?.focus()
    }
  }

  const handleKeyDown = (index: number, e: KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Backspace' && !code[index] && index > 0) {
      inputRefs.current[index - 1]?.focus()
    }
  }

  const handlePaste = (e: ClipboardEvent<HTMLInputElement>) => {
    e.preventDefault()
    const pastedData = e.clipboardData.getData('text').replace(/\D/g, '').slice(0, 6)
    if (pastedData.length > 0) {
      const newCode = [...code]
      for (let i = 0; i < pastedData.length; i++) {
        newCode[i] = pastedData[i]
      }
      setCode(newCode)
      inputRefs.current[Math.min(pastedData.length, 5)]?.focus()
    }
  }

  const handleVerify = async () => {
    const fullCode = code.join('')
    if (fullCode.length !== 6) return

    setIsLoading(true)
    try {
      // TODO: appel API de vérification MFA
      await new Promise((resolve) => setTimeout(resolve, 1500))
      router.push('/dashboard')
    } catch {
      setCode(Array(6).fill(''))
      inputRefs.current[0]?.focus()
    } finally {
      setIsLoading(false)
    }
  }

  return (
    <div
      className="bg-surface-container-low text-on-surface font-body-md min-h-screen flex flex-col"
      style={{ fontFamily: 'Inter, system-ui, sans-serif' }}
    >
      {/* ── TopNavBar (comme dans le design ERP original) ── */}
      <header className="fixed top-0 left-0 w-full z-50 flex justify-between items-center px-lg h-16 bg-surface-container-low border-b border-outline-variant">
        <div className="flex items-center gap-xs">
          <span className="text-primary font-bold text-title-lg tracking-tight">KAMLOG EM-ERP</span>
        </div>
        <div className="flex items-center gap-md">
          <div className="flex flex-col items-end hidden md:flex">
            <span className="text-label-md font-label-md text-primary uppercase tracking-widest">Secure Gateway</span>
            <span className="text-label-sm font-label-sm text-on-surface-variant">Session: Pending MFA</span>
          </div>
          <span className="material-symbols-outlined text-outline">security</span>
        </div>
      </header>

      {/* ── Main Content ── */}
      <main className="flex-grow flex items-center justify-center pt-16 px-md relative overflow-hidden">
        {/* Background */}
        <div className="absolute inset-0 z-0 opacity-40" />

        <div className="relative z-10 w-full max-w-[480px] bg-white border border-outline-variant rounded-xl shadow-sm overflow-hidden flex flex-col">

          {/* ── Header Section ── */}
          <div className="p-lg bg-surface-container-high/50 border-b border-outline-variant flex items-center gap-md">
            <div className="w-12 h-12 rounded-lg bg-primary-container flex items-center justify-center text-on-primary-container">
              <span className="material-symbols-outlined text-[28px]" style={{ fontVariationSettings: "'FILL' 1" }}>
                lock_person
              </span>
            </div>
            <div>
              <h1 className="text-headline-sm font-headline-sm text-on-surface">MFA Verification</h1>
              <p className="text-body-sm text-on-surface-variant">Two-step authentication required</p>
            </div>
          </div>

          <div className="p-lg space-y-xl">

            {!showSetup ? (
              /* ── TOTP Verification Form ── */
              <div className="space-y-lg" id="totp-view">
                <div className="space-y-xs">
                  <p className="text-body-md text-on-surface font-medium">Enter 6-digit code</p>
                  <p className="text-body-sm text-on-surface-variant leading-relaxed">
                    Enter the dynamic verification code generated by your mobile authenticator app to proceed.
                  </p>
                </div>

                {/* ── 6-digit input fields ── */}
                <div className="flex justify-between gap-xxs">
                  {code.map((digit, index) => (
                    <div key={index} className="contents">
                      {index === 3 && (
                        <div className="flex items-center text-outline-variant">
                          <span className="w-3 h-[2px] bg-current" />
                        </div>
                      )}
                      <input
                        ref={(el) => { inputRefs.current[index] = el }}
                        className="w-12 h-14 text-center text-headline-sm font-bold border border-outline-variant rounded bg-surface-container-lowest transition-all outline-none focus:border-primary focus:shadow-[0_0_0_2px_rgba(0,88,190,0.1)]"
                        inputMode="numeric"
                        maxLength={1}
                        pattern="\d*"
                        type="text"
                        value={digit}
                        onChange={(e) => handleChange(index, e)}
                        onKeyDown={(e) => handleKeyDown(index, e)}
                        onPaste={index === 0 ? handlePaste : undefined}
                      />
                    </div>
                  ))}
                </div>

                {/* ── Verify Button ── */}
                <button
                  className="w-full h-12 bg-primary text-on-primary font-bold rounded flex items-center justify-center gap-xs hover:bg-primary-container transition-all active:scale-[0.98] disabled:opacity-70"
                  onClick={handleVerify}
                  disabled={isLoading || code.join('').length !== 6}
                >
                  {isLoading ? (
                    <>
                      <span className="material-symbols-outlined animate-spin text-[20px]">sync</span>
                      <span>Verifying...</span>
                    </>
                  ) : (
                    <>
                      <span>Verify &amp; Login</span>
                      <span className="material-symbols-outlined text-[20px]">arrow_forward</span>
                    </>
                  )}
                </button>

                {/* ── Alternative actions ── */}
                <div className="pt-sm border-t border-outline-variant flex flex-col gap-sm text-center">
                  <a className="text-body-sm text-primary font-medium hover:underline flex items-center justify-center gap-xxs cursor-pointer" href="#">
                    <span className="material-symbols-outlined text-[16px]">key</span>
                    Enter backup code
                  </a>
                  <button
                    className="text-body-sm text-on-surface-variant hover:text-on-surface transition-colors flex items-center justify-center gap-xxs"
                    onClick={() => setShowSetup(true)}
                  >
                    <span className="material-symbols-outlined text-[16px]">qr_code_2</span>
                    First time? Set up QR code
                  </button>
                </div>
              </div>
            ) : (
              /* ── QR Setup View ── */
              <div className="space-y-lg" id="setup-view">
                <div className="space-y-xs">
                  <p className="text-body-md text-on-surface font-medium">Authenticator Setup</p>
                  <p className="text-body-sm text-on-surface-variant leading-relaxed">
                    Scan this QR code with Google Authenticator or Microsoft Authenticator to link your account.
                  </p>
                </div>

                <div className="flex justify-center p-md bg-white border-2 border-dashed border-outline-variant rounded-lg">
                  <div className="relative w-48 h-48">
                    <img
                      alt="MFA QR Code"
                      className="w-full h-full"
                      src="https://lh3.googleusercontent.com/aida-public/AB6AXuDIS9VvST_w4csvB_WyzL51UgVvEtNrTwb7Gz7EDGHw3EsJ_SQF3FAYEjPYHkPkL6v29rKilEMHViorLbF7h0wEzU7ISIPvtXVCNh-YjDPM3vULBB4332dbeD8iSkPKuJYYUoGk1KGa65TgLX66YoM80OP4OLWkmD4ItAywKijz7-CNVmXYh07_wz9niZH5-ebfMuoR1FaVC7OY4kPIgCGLSfnxCICCd5rQUcy0niATowDASgtqeJ0MszVaeR3hdrUFLOwHsGu_U34"
                    />
                    {/* Scanning Shimmer */}
                    <div className="absolute inset-0 pointer-events-none opacity-30" style={{
                      background: 'linear-gradient(90deg, rgba(255,255,255,0) 0%, rgba(255,255,255,0.4) 50%, rgba(255,255,255,0) 100%)',
                      backgroundSize: '200% 100%',
                      animation: 'shimmer 3s infinite linear',
                    }} />
                  </div>
                </div>

                <div className="bg-surface-container p-sm rounded border border-outline-variant/30">
                  <p className="text-label-sm font-label-sm text-on-surface-variant uppercase tracking-wider mb-xxs">Manual Secret Key</p>
                  <p className="text-data-tabular font-mono text-on-surface break-all bg-surface-container-lowest p-xs border border-outline-variant rounded select-all">
                    JBSW Y3DP EBLW 64TJ M5SS K7TG
                  </p>
                </div>

                <div className="flex gap-sm">
                  <button
                    className="flex-1 h-11 border border-outline text-on-surface font-medium rounded hover:bg-surface-container-high transition-all"
                    onClick={() => {
                      setShowSetup(false)
                      setTimeout(() => inputRefs.current[0]?.focus(), 100)
                    }}
                  >
                    Back to Verify
                  </button>
                  <button className="flex-1 h-11 bg-primary text-on-primary font-bold rounded hover:bg-primary-container transition-all">
                    Complete Setup
                  </button>
                </div>
              </div>
            )}
          </div>

          {/* ── Footer Compliance ── */}
          <div className="px-lg py-md bg-surface-container-lowest text-center">
            <p className="text-label-sm font-label-sm text-on-surface-variant">KAMLOG Secure Access Control © 2026</p>
            <div className="flex justify-center gap-md mt-xxs">
              <span className="text-label-sm text-outline flex items-center gap-xxs">
                <span className="material-symbols-outlined text-[14px]" style={{ fontVariationSettings: "'FILL' 1" }}>verified_user</span>
                ISO 27001 Compliant
              </span>
            </div>
          </div>
        </div>
      </main>

      {/* ── Visual Identity Strip (bottom of screen) ── */}
      <div className="fixed bottom-0 left-0 w-full h-1 bg-primary flex">
        <div className="h-full bg-secondary w-1/4" />
        <div className="h-full bg-tertiary-container w-1/4" />
        <div className="h-full bg-primary w-2/4" />
      </div>

      {/* Shimmer animation keyframes */}
      <style jsx>{`
        @keyframes shimmer {
          0% { background-position: -200% 0; }
          100% { background-position: 200% 0; }
        }
      `}</style>
    </div>
  )
}
